### ISSUE TITLE
IllegalArgumentException: Can not set static XXX field

### ISSUE THREAD

**Issue by zyw19871007** [core-lib/xjar-agent-hibernate#2]
Caused by: java.lang.IllegalArgumentException: Can not set static io.xjar.agent.hibernate.XJarHibernateInterceptor field org.hibernate.boot.archive.internal.JarFileBasedArchiveDescriptor.delegate$qrs2da0 to io.xjar.agent.hibernate.XJarHibernateInterceptor
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
        at sun.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:81)
        at java.lang.reflect.Field.set(Field.java:764)
        at net.bytebuddy.implementation.LoadedTypeInitializer$ForStaticField.onLoad(LoadedTypeInitializer.java:124)
        at net.bytebuddy.implementation.LoadedTypeInitializer$Compound.onLoad(LoadedTypeInitializer.java:187)
        at net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Dispatcher$InjectingInitializer.onLoad(AgentBuilder.java:3144)
        ... 145 common frames omitted

**Comment by zyw19871007** [comment]
找到一个类似问题 https://github.com/raphw/byte-buddy/issues/113  但是对反射不熟，看不懂。
请求帮助啊
